version: '3.4'

services:
  weatherapp:
    image: weatherapp
    build: .\weatherapi
    ports:
        - "51000:50001"
        - "8081:80"

  weatherapp-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "weatherapp", "-app-port", "80" ]
    depends_on:
      - weatherapp
    network_mode: "service:weatherapp"

  weatherstore:
    image: weatherstore
    build: .\weather-store
    ports:
        - "52000:50001"

  weatherstore-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "weatherstore", "-app-port", "80" ]
    depends_on:
      - weatherstore
    network_mode: "service:weatherstore"