apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: weatherstore
  name: weatherstore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weatherstore
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: weatherstore
    spec:
      containers:
        - image: weatherstore
          name: weatherstore
          ports:
            - containerPort: 50001
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always      
status: {}
