apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: weatherstore
  name: weatherstore
spec:
  ports:
    - name: "52000"
      port: 52000
      targetPort: 50001
  selector:
    io.kompose.service: weatherstore
